"use client";

import memoji from "@/assets/avatar/memoji.png";
import { Locale, useLocale } from "next-intl";
import Image from "next/image";
import { useState } from "react";
import { Tooltip, TooltipContent, TooltipTrigger } from "./Tooltip";

const phrases = {
	en: [
		"You found the easter egg 🥚",
		"Don't click, I might deploy 😎",
		"Yes, that's me!",
		"Hard to miss, right? 👀",
		"This code won't write itself... or will it? 🤖",
		"Tea? Coffee? Commit? ☕️",
		"Error? Not today 💪",
		"Updating reality 🌍",
		"Debug is my lifestyle",
		"One more build, then sleep 😴",
		"Are you a frontend dev too?",
		"Hunting bugs? 🐛",
		"CMD + S is my reflex",
		"Told you it works!",
		"Not broken, just napping 😌",
		"If I were a miracle, I'd be in production",
		"You can call me like a hook 😉",
		"Pinging mood server...",
		"A memoji with a soul",
		"No AI here, it's really me 🧠",
		"Deploy complete ✅",
		"Built with love and Tailwind ❤️",
		"Just a bit of caffeine and we're good 🚀",
		"Don't touch my code 😅",
		'console.log("Hello, world!")',
		"A little refactor never hurt anyone",
		"You can only see me here 👋",
		"CSS is magic, don't argue",
		"Pixel-perfect - just like me",
		"Watch closely... commit incoming",
		"Lost internet, lost hope 😭",
		"Who's the UI boss?",
		"Secret element discovered 🔍",
		"Hover again for focus 🎯",
		"I'm not a bug, I'm a feature",
		"A few more components and it's production-ready",
		"async function life() { await coffee(); } ☕️",
		"All under control (React Hook Form approved)",
		"API says hi! 👋",
		"Tested on prod... probably",
		"Dancing with Tailwind 💃🕺🏼",
		"Optimization on the way 🚗",
		"Product of 9999 commits",
		"Powered by shadcn/ui ⚡️",
		"This could've been an ad",
		"Design or code? Why not both?",
		"Greetings from staging 👋",
		"Committed with love ❤️",
		"Wish useEffect ran smoother",
		"If you're reading this - you're breathtaking 🦾😎",
		"Bug? Haven't seen one here 👀",
		"If I disappear, I'm in the console 🖥️",
		"You can't uninstall me with npm 😅",
		"Another day, another deploy 🚀",
		"Code lives as long as useEffect runs",
		"Are you QA or just curious? 🧐",
		"No tests, just faith 🙏",
		"Coding on coffee, surviving on deadlines ☕️⏰",
		"Tailwind hugged me 💨",
		"Backend promised it'll be fine",
		"Three commits = one coffee ☕️",
		"Random console.log() is never random",
		"Dreaming of a conflict-free merge 🧘",
		"Don't worry, it's just staging 😬",
		"Syntactic sugar is my weakness 🍭",
		"If it works - don't touch it 😅",
		"No one's perfect, but my linter is close",
		"My commits speak louder than words 💬",
		"Love the smell of fresh build in the morning ☀️",
		"Code like your future self will read it",
		"Leaving comments... for myself 🤫",
		"A bug-free evening is a celebration 🎉",
		"Another release, another prayer 🙏",
		"I'm not a freelancer, I'm a one-man deploy 😎",
		"When it works - it's a miracle ✨",
		"Order in code, chaos in mind 🤯",
		"If it broke - it must've worked before 😉",
		"Everything's cached, even emotions 💾",
		"Don't forget the semicolon!",
		"Seriously, I tested it... on prod 😅",
		"While others sleep, I push 🧑‍💻",
		"Sometimes I think code is poetry",
		"Half my life is waiting for npm install",
		"If it's fast - thank Next.js ⚡️",
		"Backend said “soon”, it's been a week 😭",
		"UI without UX is like code without return",
		"Not lazy, just caching ideas 💤",
		"Don't forget to pull before commit 😉",
		"React is my therapy 🧠",
		"CSS has a mind of its own 🎨",
		"I've seen worse code... mine from last year 😬",
		"A little Tailwind makes everything prettier 🌈",
		"A bug-free release is a myth 🧙‍♂️",
		"Please not prod, not prod 😨",
		"It's not a bug, it's a surprise 🎁",
		"Compiled with love ❤️",
		"Don't forget to update your dependencies 🧩",
		"Code cleaner than my conscience ✨",
		"Created by Yevhen - tested in production 😅"
	],
	uk: [
		"Ви знайшли пасхалку 🥚",
		"Не клікай, бо запущу деплой 😎",
		"Так, це я!",
		"Мене важко не помітити 👀",
		"Цей код сам себе не напише... або напише 🤖",
		"Чай? Кава? Коміт? ☕️",
		"Помилка? Не сьогодні 💪",
		"Працюю над апдейтом реальності 🌍",
		"Debug - це спосіб життя",
		"Ще один білд, і спати 😴",
		"Ти точно фронтендер?",
		"Ти теж шукаєш баги? 🐛",
		"CMD + S - це мій рефлекс",
		"Я ж казав, що воно працює!",
		"Я не зламаний, просто у сплячці 😌",
		"Якби я був дивом, то в продакшені",
		"Мене можна викликати як хук 😉",
		"Пінгую сервер настрою...",
		"Я - мемодзі, але з душею",
		"Ні, це не AI, це справжній я 🧠",
		"Deploy complete ✅",
		"Мене зібрано з любов’ю і Tailwind ❤️",
		"Трохи кофеїну - і все буде 🚀",
		"Don’t touch my code 😅",
		'console.log("Привіт, світе!")',
		"Легкий рефакторинг ще нікому не шкодив",
		"Мене можна побачити тільки тут 👋",
		"CSS - це магія, не сперечайся",
		"Піксель ідеальний, як я",
		"Уважно дивись... зараз буде commit",
		"Зник інтернет - зникла надія 😭",
		"Хто тут головний по UI?",
		"Секретний елемент знайдено 🔍",
		"Наведи ще раз - і буде фокус 🎯",
		"Я не баґ, я фіча",
		"Ще пару компонентів і можна в прод",
		"async function life() { await coffee(); } ☕️",
		"Все під контролем (підтверджено React Hook Form)",
		"API каже “hi! 👋”",
		"Протестовано на проді... можливо",
		"Танцюю з Tailwind 💃🕺🏼",
		"Оптимізація? Уже в дорозі 🚗",
		"Я - результат 9999 комітів",
		"Працює на shadcn/ui ⚡️",
		"Тут могла бути реклама",
		"Дизайн чи код? Чому не те і те?",
		"Привіт із staging середовища 👋",
		"Коміт з любов’ю ❤️",
		"От зараз би useEffect без зависань",
		"Якщо ви це читаєте - ви чудові 🦾😎",
		"Баґ? Не бачив такого тут 👀",
		"Якщо я зник - я в консолі 🖥️",
		"Мене не можна видалити через npm uninstall 😅",
		"Ще один день - ще один деплой 🚀",
		"Код живе, поки працює useEffect",
		"Ви точно не QA? 🧐",
		"Тестів немає, але віра є 🙏",
		"Кодую під каву, живу під дедлайни ☕️⏰",
		"Tailwind мене обійняв 💨",
		"Бекенд обіцяв, що все буде добре",
		"Зробив три коміти - заслужив каву ☕️",
		"Випадковий console.log() - не випадковий",
		"Зараз би merge без конфліктів 🧘",
		"Не хвилюйся, це лише staging 😬",
		"Синтаксичний цукор - моя слабкість 🍭",
		"Якщо працює - не чіпай 😅",
		"Ніхто не ідеальний, але мій лінтер близько",
		"Мої коміти говорять самі за себе 💬",
		"Люблю запах свіжого білду вранці ☀️",
		"Пиши код, ніби тебе читає майбутній ти",
		"Залишаю коментарі тільки для себе 🤫",
		"Вечір без помилок - це свято 🎉",
		"Ще один реліз - ще одна молитва 🙏",
		"Я не фрілансер, я сам собі деплой 😎",
		"Коли все працює - це вже диво ✨",
		"В коді - порядок, у голові - merge conflict 🤯",
		"Якщо воно зламалось - значить працювало 😉",
		"У мене все кешується, навіть емоції 💾",
		"Головне - не забути поставити ;",
		"Серйозно, я тестував це… на проді 😅",
		"Поки інші сплять - я пушу 🧑‍💻",
		"Іноді я думаю, що код - це поезія",
		"Половину часу я просто чекаю на npm install",
		"Якщо сайт швидкий - це все Next.js ⚡️",
		"Бекенд каже «soon», я вже тиждень чекаю 😭",
		"UI без UX - як код без return",
		"Я не лінуюсь, я просто кешую ідеї 💤",
		"Не забудь зробити pull перед комітом 😉",
		"React - моя терапія 🧠",
		"CSS має власну свідомість 🎨",
		"Я бачив код гірший... свій минулорічний 😬",
		"Трохи Tailwind і все стає красивішим 🌈",
		"Реліз без баґів - легенда 🧙‍♂️",
		"Тільки не prod, тільки не prod 😨",
		"Це не баґ, це сюрприз 🎁",
		"Я компілююсь із любов’ю ❤️",
		"Не забудь оновити dependencies 🧩",
		"Код чистіший за моє сумління ✨",
		"Створено Євгеном - протестовано у продакшені 😅"
	]
};

const selectRandomPhrase = (locale: Locale) => {
	return phrases[locale][Math.floor(Math.random() * phrases[locale].length)];
};

function FooterImage() {
	const [phrase, setPhrase] = useState("");
	const locale = useLocale();

	const changePhrase = () => setPhrase(selectRandomPhrase(locale));

	return (
		<Tooltip>
			<TooltipTrigger>
				<div className="pattern-dots-md text-edge">
					<Image
						src={memoji}
						alt=""
						width={100}
						height={100}
						className="border-edge border-x"
						onMouseEnter={changePhrase}
					/>
				</div>
			</TooltipTrigger>
			<TooltipContent>{phrase}</TooltipContent>
		</Tooltip>
	);
}

export default FooterImage;
